Add intro
geodynamics/pylith pull request #343
Opened 2021-08-03 19:04 UTC by cmills1095

Figure would not work unless I added a .jpg version to the 'figs' folder and changed the command to img src="figs/workflow.jpg". More version numbers that would need to be manually updated in this page as well.

2021-08-03 20:34 UTC, ljhwang commented
You may want to check to see what 'default-image-extension' is set to in default.yaml.

That being said, I never got it to work properly.

@baagaard Should we keep a version number in the section title?  We may want to update this in as few places as possible.

2021-08-03 21:40 UTC, baagaard-usgs requested changes
A couple requested changes:

Use `*` for bullet lists instead of `-` and put only 1 space between `*` and the text. No need to put a blank line between bulleted items.

New utilities: Use bullets for list.

Replace "The `CHANGES.md` file in the top-level source directory contains a summary of features and bug fixes for each release." with "See [Release Notes](release-notes.md] for a summary of features and bug fixes for each release."

I believe {numref}`fig:workflow:summary` will automatically include "Fig. #" so you don't need "Figure {numref}`fig:workflow:summary`.

Change "fig:Workflow-summary" to "fig:workflow:summary". You should be able to use src="figs/workflow.*" in the figure.

2021-08-03 22:06 UTC, baagaard-usgs approved these changes

2021-08-04 02:03 UTC, baagaard-usgs commented
@ljhwang There are only a few files that have the version number. The main places are in the intro and installation instructions. It is easy enough to use grep to find these places.

2021-08-04 02:03 UTC, merged