Multi constraints
geodynamics/pylith pull request #357
Opened 2021-09-24 18:42 UTC by rwalkerlewis

Adjusts createConstraint functions to return a vector of constraints (createConstraints)

2021-09-29 01:47 UTC, baagaard-usgs commented
I suggest rebasing on `main` to see if this passes now. I pushed fixes to the fault residual to `main`.

2021-09-30 02:43 UTC, rwalkerlewis commented
Looks like that fixed it.

2021-09-30 03:04 UTC, baagaard-usgs commented on libsrc/pylith/problems/Problem.cc
> +        if (constraints.size() > 0) {
I don't think you need the outer `if (constraints.size() > 0)`.

2021-09-30 03:05 UTC, baagaard-usgs commented on libsrc/pylith/problems/Problem.cc
> +        // assert(count < maxSize);
Please remove the obsolete code rather than just commenting it out.

2021-09-30 03:15 UTC, baagaard-usgs commented on libsrc/pylith/bc/AbsorbingDampers.cc
> +    constraintArray.resize(0);
Please remove these `resize(0)` lines. The array already has a size of 0.

2021-09-30 03:17 UTC, baagaard-usgs requested changes
Looks good. Just a few minor changes requested to tidy things up.

2021-09-30 14:20 UTC, baagaard-usgs requested changes
There are multiple instances of `constraintArray.resize(0);`. It looks like you only removed one.

Check:
libsrc/pylith/bc/NeumannTimeDependent.cc
libsrc/pylith/bc/NeumannUserFn.cc
libsrc/pylith/faults/FaultCohesiveKin.cc
libsrc/pylith/testing/PhysicsStub.cc

It looks like you also missed my requested change for Problem.cc:
Here is simpler code that replaces lines 459-466 and related lines.

```
_constraints.insert(_constraints.end(), constraints.begin(), constraints.end());
```

2021-09-30 17:48 UTC, rwalkerlewis commented
I made the change for Problem.cc

2021-09-30 17:54 UTC, baagaard-usgs approved these changes
Thanks! Waiting for the CI tests to run.

2021-09-30 18:16 UTC, baagaard-usgs commented
Hmm. Something went awry. The std::vector::insert() should work. Can you verify in the debugger that the Constraint* are getting copied over into `_constraints`?

2021-09-30 19:27 UTC, baagaard-usgs commented
The problem is https://github.com/geodynamics/pylith/blob/b8ca82f3cc4122a440d8fd453a264d27df0bf793/libsrc/pylith/problems/Problem.cc#L451.

Change to `_constraints.resize(0); // insure we start with an empty array.`

2021-09-30 20:46 UTC, merged